# Hyprland configuration
# https://wiki.hyprland.org/

# Variables
$mod = SUPER
$terminal = ghostty
$file_manager = dolphin
$ss = hyprshot

# Source modular configs
source = $HOME/.config/hypr/monitors.conf
source = $HOME/.config/hypr/input.conf
source = $HOME/.config/hypr/autostart.conf
source = $HOME/.config/hypr/appearance.conf
source = $HOME/.config/hypr/keybinds.conf
