# AppleII hardware configuration (generated by nixos-generate-config)
{ lib, ... }:
{
  flake.modules.nixos.AppleII-hardware = { config, lib, modulesPath, ... }: {
    imports = [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-amd" ];
    boot.extraModulePackages = [ ];

    fileSystems."/" = {
      device = "/dev/disk/by-uuid/8b0dcc20-084d-4b6f-98e9-844ecf6a28b4";
      fsType = "ext4";
    };

    fileSystems."/boot" = {
      device = "/dev/disk/by-uuid/8CB6-0443";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

    swapDevices = [
      { device = "/dev/disk/by-uuid/54608045-2f05-4a2f-842d-79d7bf571c59"; }
    ];

    # Enable hibernate resume from the swap partition above (swap 102G > 93G RAM).
    # Without this the kernel has no resume pointer and boots fresh, losing state.
    boot.resumeDevice = "/dev/disk/by-uuid/54608045-2f05-4a2f-842d-79d7bf571c59";

    networking.useDHCP = lib.mkDefault true;
    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
